[package]
name = "autocommit-rs"
version = "0.1.0"
authors = ["Louis Pontoise <lwouis@gmail.com>"]

[dependencies]
git2 = "0.6.6"
serde = "1.0.11"
serde_json = "1.0.2"
serde_derive = "1.0.11"
log = "0.3.8"
env_logger = "0.4.3"
time = "0.1.38"
notify = "4.0.0"
fs_extra = "1.0.0"